from enum import Enum

class AgentState(str, Enum):
    IDLE = "IDLE"
    UNDERSTANDING = "UNDERSTANDING"
    PLANNING = "PLANNING"
    WAITING_FOR_CLARIFICATION = "WAITING_FOR_CLARIFICATION"
    RESEARCHING = "RESEARCHING"
    EXECUTING = "EXECUTING"
    WAITING_FOR_CONFIRMATION = "WAITING_FOR_CONFIRMATION"
    VERIFYING = "VERIFYING"
    CHALLENGING = "CHALLENGING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
